orders/urls.py
from django.urls import path

from .views import (OrderCreateView, OrdersListView, OrderView,
                    SuccessOrderCreateView)

app_name = 'app_orders'

urlpatterns = [
    path('', OrdersListView.as_view(), name='show'),
    path('order/<int:orderID>', OrderView.as_view(), name='order'),
    path('create/', OrderCreateView.as_view(), name='create'),
    path('success/', SuccessOrderCreateView.as_view(), name='success'),
]

store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from products.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),

    path('', IndexView.as_view(), name='index'),
    path('products/', include('products.urls', namespace='ns_products')),
    path('users/', include('users.urls', namespace='users')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('api/', include('common.api_urls')),
]

if settings.DEBUG:
    urlpatterns = [
        path('__debug__/', include('debug_toolbar.urls'))
    ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
from django.db import models

from users.models import User


class Orders(models.Model):

    """Описывает сущность заказ

    Атрибуты:
        1. first_name - имя получателя
        2. last_name - фамилия получателя
        3. email - адрес электронной почты для связи
        4. address - адрес доставки
        5. created - дата и время оформления заказа. Заполняется автоматически при добавлении записи в БД
        6. user - пользователь, который оформил заказ. Связь Один-со-Многими. Первичная модель - User
        7. status - статус заказа. Перечисление с целочисленными внутренними значениями
        8. buscets - товары, из которых состоит заказ
        9. to_pay - сумма к оплате за заказ

    """

    class Status(models.IntegerChoices):

        """Описывает перечисление с целочисленными внутренними значениями"""

        ACCEPTED = 0, 'Принят'
        PAID = 1, 'Оплачен'
        TRANSIT = 2, 'В пути'
        DELIVERED = 3, 'Доставлен'

    first_name = models.CharField('Имя', max_length=50)
    last_name = models.CharField('Фамилия', max_length=50)
    email = models.EmailField('E-mail')
    address = models.TextField('Адрес', max_length=500)
    created = models.DateTimeField('Дата создания', auto_now_add=True)
    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name='orders',
        related_query_name='order',
        null=True,
        blank=True,
        verbose_name='Оформил'
    )
    status = models.PositiveSmallIntegerField('Статус заказа', choices=Status.choices,
                                              default=Status.ACCEPTED)
    buscets = models.JSONField('Товары', default=dict)
    to_pay = models.PositiveIntegerField('К оплате', default=0)

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return f"Заказ #{self.id} | {self.first_name} {self.last_name} | {self.get_status_display()}"

orders/forms.py
from django import forms

from .models import Orders

LABEL_FORM_CONTROL = 'form-control'
LABEL_ATTR_CLASS = 'class'
LABEL_ATTR_PLACEHOLDER = 'placeholder'


class OrdersForm(forms.ModelForm):

    """Описывает форму оформления заказа.

   OrdersForm является формой, связанной с моделью. Модель - Orders.
   Атрибуты(поля формы):
       1. first_name - имя получателя заказа. Получателем не обязательно должен быть человек, который
          оформляет заказ
       2. last_name - фамилия получателя заказа
       3. email - адрес электронной почты для связи
       4. address - адрес доставки

    """
    first_name = forms.CharField(
        required=True,
        max_length=50,
        widget=forms.widgets.TextInput(
            attrs={
                LABEL_ATTR_CLASS: LABEL_FORM_CONTROL,
                LABEL_ATTR_PLACEHOLDER: 'Иван',
            }
        )
    )
    last_name = forms.CharField(
        required=True,
        max_length=100,
        widget=forms.widgets.TextInput(
            attrs={
                LABEL_ATTR_CLASS: LABEL_FORM_CONTROL,
                LABEL_ATTR_PLACEHOLDER: 'Иванов',
            }
        )
    )
    email = forms.EmailField(
        required=True,
        max_length=50,
        widget=forms.widgets.EmailInput(
            attrs={
                LABEL_ATTR_CLASS: LABEL_FORM_CONTROL,
                LABEL_ATTR_PLACEHOLDER: 'you@example.com',
            }
        )
    )
    address = forms.CharField(
        required=True,
        max_length=500,
        widget=forms.widgets.TextInput(
            attrs={
                LABEL_ATTR_CLASS: LABEL_FORM_CONTROL,
                LABEL_ATTR_PLACEHOLDER: 'Россия, Москва, ул. Мира, дом 6',
            }
        )
    )

    class Meta:
        model = Orders
        fields = (
            'first_name',
            'last_name',
            'email',
            'address',
        )

orders/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, ListView, TemplateView

from common.views import CommonMixin
from products.models import Buscet

from .forms import OrdersForm
from .models import Orders


class OrderCreateView(CommonMixin, CreateView):

    """Выводит форму создания заказа, выполняет ее валидацию и добавляет запись в БД.

    Класс-контроллер унаследован от класса-контроллера CreateView.
    Выполнено переопределение метода form_valid() суперкласса с целью
    добавления в запись значений полей, отсутствующих в форме.
    Атрибуты:
        1. title - заголовок страницы. Атрибут предоставляется миксином CommonMixin
        2. template_name - путь к файлу шаблона, сощдающего страницу с формой
        3. form_class - ссылка на класс используемой формы
        4. success_url - адрес для перенаправления в случае успешной валидации формы

    """

    title = 'Store - Оформление заказа'
    template_name = 'orders/order-create.html'
    form_class = OrdersForm
    success_url = reverse_lazy('orders:success')

    def form_valid(self, form):
        """Вычисляет значения отсутствующих в форме полей, выполняет валидацию формы, удаляет корзину.

        1. Вычисляет значения полей user, buscets, to_pay перед операцией валидации формы
        2. Выполняет метод form_valid() суперкласса
        3. В случае успешной валидации, удаляет корзину пользователя

        """
        form.instance.user = self.request.user
        buscets = Buscet.objects.select_related('product').filter(
            user=self.request.user
        )

        Buscet.objects.select_related(None)

        form.instance.buscets = buscets.serialize_json()

        form.instance.to_pay = buscets.values(
            'total',
            'product__price',
        ).calc_total_price()

        response = super(OrderCreateView, self).form_valid(form)
        buscets.delete()

        return response


class SuccessOrderCreateView(CommonMixin, TemplateView):

    """Выполняет рендеринг шаблона"""

    title = 'Store - Спасибо за заказ!'
    template_name = 'orders/order-success.html'


class OrdersListView(CommonMixin, ListView):

    """Отображает список заказов пользователя

    Заказы отсортированы по дате создания.
    Результат запроса помещается в переменную контекста шаблона 'orders'.
    Переопределен метод суперкласса get_queryset()
    Атрибуты:
        1. model - модель, используемая для выполнения запросов
        2. template_name - путь к файлу шаблона, создающего страницу с формой
        3. context_object_name - переменная контекста, содержащая результат запроса
        4. ordering - поле, по которому будет выполнена сортировка
        5. title - заголовок страницы. Атрибут предоставляется миксином CommonMixin

    """

    model = Orders
    template_name = 'orders/orders.html'
    context_object_name = 'orders'
    ordering = ('-created',)
    title = 'Store - Заказы'

    def get_queryset(self):
        """Возвращает список заказов, принадлежащих определенному пользователю"""
        return super(
            OrdersListView,
            self
        ).get_queryset().filter(
            user=self.request.user
        )


class OrderView(DetailView):

    """Отображает детали определенного товара.

    Атрибуты:
        1. model - модель, используемая для выполнения запросов
        2. pk_url_kwarg - наименование URL-параметра для извлечения ключа записи
        3. template_name - путь к файлу шаблона, сощдающего страницу с формой
        4. context_object_name - переменная контекста, содержащая результат запроса

    """

    model = Orders
    pk_url_kwarg = 'orderID'
    template_name = 'orders/order.html'
    context_object_name = 'order'

orders/templates/orders/order-create.html
{% extends 'products/base.html' %}
{% load humanize %}
{% block title %}{{title}}{% endblock %}
{% block content %}
<section>
    <div class="alert alert-warning text-center" role="alert">
        Пожалуйста, заполните адрес электронной почты.
    </div>
    <div class="container">
        <div class="py-5 text-center">
            <h1>Оформление заказа</h1>
        </div>
        <div class="row g-5">
            <div class="col-md-5 col-lg-4 order-md-last">
                <h4 class="d-flex justify-content-between align-items-center mb-3">
                    <span class="text-primary">Корзина</span>
                    <span class="badge badge-primary badge-pill text-white">{{ buscets.calc_total_products }}</span>
                </h4>
                <ul class="list-group mb-3">
                    {% for buscet in buscets %}
                    <li class="list-group-item d-flex justify-content-between lh-sm">
                        <div>
                            <h6 class="my-0">{{ buscet.product__name}}</h6>
                            <small class="text-muted">{{ buscet.total }} шт.</small>
                        </div>
                        <span class="text-muted">{{ buscet.price|intcomma }} руб.</span>
                    </li>
                    {% endfor %}
                    <li class="list-group-item d-flex justify-content-between">
                        <span>Сумма к оплате</span>
                        <strong>{{ buscets.calc_total_price|intcomma }} руб.</strong>
                    </li>
                </ul>
            </div>
            <div class="col-md-7 col-lg-8">
                <h4 class="mb-3">Адрес доставки</h4>
                <form action="{% url 'orders:create' %}" method="post">{% csrf_token %}
                    <div class="row g-3">
                        <div class="col-sm-6">
                            <label class="form-label" for={{form.first_name.id_for_label}}>Имя</label>
                            {{form.first_name}}
                        </div>

                        <div class="col-sm-6">
                            <label class="form-label" for={{form.last_name.id_for_label}}>Фамилия</label>
                            {{form.last_name}}
                        </div>

                        <div class="col-12 mt-3">
                            <label class="form-label" for={{form.email.id_for_label}}>Адрес электронной почты</label>
                            {{form.email}}
                        </div>

                        <div class="col-12 mt-3">
                            <label class="form-label" for={{form.address.id_for_label}}>Адрес</label>
                            {{form.address}}
                        </div>

                        <hr class="my-4">
                        <button class="w-100 btn btn-primary btn-lg" type="submit">Продолжить</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

orders/templates/orders/order-success.html
{% extends 'products/base.html' %}
{% load static %}
{% block title %}{{title}}{% endblock %}
{% block t_styles %}
<link href="{% static 'vendor/css/auth.css' %}" rel="stylesheet"/>
{% endblock %}
{% block content %}
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        <main>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-5">
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header">
                                <h3 class="text-center font-weight-light my-4">Спасибо за заказ!</h3>
                            </div>
                            <div class="card-body text-center">
                                <h4>
                                    Ваш заказ успешно сформирован.
                                </h4>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>
{% endblock %}

orders/templates/orders/order.html
{% extends 'products/base.html' %}
{% load static %}
{% load humanize %}
{% block title %}{{ title }}{% endblock %}
{% block t_style %}<link href="{% static 'vendor/css/orders.css' %}" rel="stylesheet">{% endblock %}
{% block content %}
<section>
    <div class="container pt-5">
        <div class="text-center mt-5">
            <h1>Заказ № {{ order.id }}</h1>
            <div class="orders mt-5">
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">Название</th>
                        <th scope="col">Кол-во</th>
                        <th scope="col">Цена</th>
                        <th scope="col">Сумма</th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for buscet in order.buscets %}
                            <tr>
                                <th scope="row">
                                    {{ buscet.product__name }}
                                </th>
                                <td>{{ buscet.total }}</td>
                                <td>{{ buscet.product__price|intcomma }} руб.</td>
                                <td>{{ buscet.price|intcomma }} руб.</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <p class="float-right h4 mt-3">Итого {{ order.to_pay|intcomma }} руб.</p>
            </div>
        </div>
    </div>
</section>
{% endblock %}

orders/templates/orders/orders.html
{% extends 'products/base.html' %}
{% load static %}
{% load humanize %}
{% block title %}{{ title }}{% endblock %}
{% block t_styles %}<link href="{% static 'vendor/css/orders.css' %}" rel="stylesheet">{% endblock %}
{% block content %}
<section>
    <div class="container pt-5">
        <div class="text-center mt-5">
            <h1>Заказы</h1>
            <div class="orders mt-5">
                <table class="table">
                    <thead>
                    <tr class="table-light">
                        <th scope="col">#</th>
                        <th scope="col">Статус</th>
                        <th scope="col">Создан</th>
                        <th scope="col">Итого</th>
                        <th scope="col">Действие</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for order in orders %}
                        <tr>
                            <th scope="row">{{ order.id }}</th>
                            <td>{{ order.get_status_display }}</td>
                            <td>{{ order.created|naturaltime }}</td>
                            <td>{{ order.to_pay|intcomma }} руб.</td>
                            <td>
                                <a href="{% url 'orders:order' order.id %}">Детали</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
{% endblock %}