orders/urls.py
from django.urls import path

from .views import (OrderCreateView, OrdersListView, OrderView,
                    SuccessOrderCreateView)

app_name = 'app_orders'

urlpatterns = [
    path('', OrdersListView.as_view(), name='show'),
    path('order/<int:orderID>', OrderView.as_view(), name='order'),
    path('create/', OrderCreateView.as_view(), name='create'),
    path('success/', SuccessOrderCreateView.as_view(), name='success'),
]

products/urls.py
from django.urls import path

from .views import ProductListView, add_product, remove_product

app_name = 'products'

urlpatterns = [
    path('', ProductListView.as_view(), name='prod_page'),
    path('category/<int:categoryID>/', ProductListView.as_view(), name='category'),
    path('buscet/add/<int:product_id>/', add_product, name='add_product'),
    path('buscet/remove/<int:buscet_id>/', remove_product, name='remove_product'),
]

store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from products.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),

    path('', IndexView.as_view(), name='index'),
    path('products/', include('products.urls', namespace='ns_products')),
    path('users/', include('users.urls', namespace='users')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('api/', include('common.api_urls')),
]

if settings.DEBUG:
    urlpatterns = [
        path('__debug__/', include('debug_toolbar.urls'))
    ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from .views import (UserRegisterView, UsersConfirmationView, UsersLoginView,
                    UsersUpdateView)

app_name = 'app_users'

urlpatterns = [
    path('login/', UsersLoginView.as_view(), name='login'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('profile/<int:pk>/', UsersUpdateView.as_view(), name='profile'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('confirm-email/<uuid:code>/', UsersConfirmationView.as_view(), name='confirm'),
]

products/views.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpRequest, HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django_filters.rest_framework import DjangoFilterBackend
from drf_spectacular.utils import (OpenApiParameter, extend_schema,
                                   extend_schema_view)
from rest_framework import status
from rest_framework.viewsets import ModelViewSet

from common.permissions import ApiUserPermission
from common.views import CommonMixin

from .models import Buscet, Product, ProductCategory
from .serializers import (DetailMessageSerializer, ProductCategorySerializer,
                          ProductSerializer)


class IndexView(CommonMixin, TemplateView):

    """Выполняет рендеринг шаблона"""

    template_name = 'products/index.html'
    title = 'Store'


class ProductListView(CommonMixin, ListView):
    """Отображает список товаров в каталоге.

    Товары отсортированы по наименованию.
    Результат запроса помещается в переменную контекста шаблона 'products'.
    Переопределены следующие методы суперкласса:
        1. get_queryset()
        2. get_context_data()
    Атрибуты:
        1. model - модель, используемая для выполнения запросов
        2. template_name - путь к файлу шаблона, создающего страницу с формой
        3. context_object_name - переменная контекста, содержащая результат запроса
        4. ordering - поле, по которому будет выполнена сортировка
        5. title - заголовок страницы. Атрибут предоставляется миксином CommonMixin
        6. paginate_by - число товаров в одной части пагинатора

    """
    model = Product
    template_name = 'products/products.html'
    context_object_name = 'products'
    ordering = ('name',)
    title = 'Store - Каталог'
    paginate_by = 2

    def get_queryset(self):
        """Возвращает список товаров.

        Если в URL присутствует параметр, указывающий на определенную категорию товаров,
        то набор записей будет состоять только из товаров указанной категории.
        Если категория не указана, то набор записей будет содержать товары всех категорий.
        Если указана категория, которая не существует или не имеющая товаров, будет возвращена 404

        """
        category_id = self.kwargs.get('categoryID')
        queryset = self.model.objects.filter(category_id=category_id) if category_id else self.model.objects.all()
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        """Добавляет в контекст переменную, содержащую список категорий товаров"""
        context = super().get_context_data(**kwargs)
        context['categories'] = ProductCategory.objects.all()
        return context


@extend_schema(tags=['Products'])
@extend_schema_view(
    list=extend_schema(
        operation_id='api_products_list',
        summary='Получить список товаров',
        description=' ',
        responses={
            (status.HTTP_200_OK, 'application/json'): ProductSerializer,
            (status.HTTP_401_UNAUTHORIZED, 'application/json'): DetailMessageSerializer,
        },
        parameters=[
            OpenApiParameter(
                name='category',
                location=OpenApiParameter.QUERY,
                required=False,
                description='id категории',
                type=int
            ),
        ]
    ),
    retrieve=extend_schema(
        operation_id='api_products_by_category_list',
        summary='Получить товар по id',
        description=' ',
        parameters=[
            OpenApiParameter(
                name='id',
                type=int,
                location=OpenApiParameter.PATH,
                required=True,
                description='id товара'
            )
        ],
        responses={
            (status.HTTP_200_OK, 'application/json'): ProductSerializer,
            (status.HTTP_401_UNAUTHORIZED, 'application/json'): DetailMessageSerializer,
            (status.HTTP_404_NOT_FOUND, 'application/json'): DetailMessageSerializer,
        }
    ),
    create=extend_schema(
        operation_id='api_products_create',
        summary='Добавить товар',
        description=' ',
        responses={
            (status.HTTP_201_CREATED, 'application/json'): ProductSerializer,
            (status.HTTP_401_UNAUTHORIZED, 'application/json'): DetailMessageSerializer,
            (status.HTTP_403_FORBIDDEN, 'application/json'): DetailMessageSerializer
        }
    ),
    destroy=extend_schema(
        operation_id='api_products_destroy',
        summary='Удалить товар',
        description=' ',
        parameters=[
            OpenApiParameter(
                name='id',
                type=int,
                location=OpenApiParameter.PATH,
                required=True,
                description='id товара, который необходимо удалить'
            )
        ],
        responses={
            status.HTTP_204_NO_CONTENT: None,
            (status.HTTP_401_UNAUTHORIZED, 'application/json'): DetailMessageSerializer,
            (status.HTTP_403_FORBIDDEN, 'application/json'): DetailMessageSerializer
        }
    )

)
class ApiProductsViewSet(ModelViewSet):

    """Возвращает ресурс-перечень товаров или ресурс-перечень товаров отдельной категории

    Переопределены атрибуты:
        1. queryset - набор записей
        2. serializer_class - ссылка на класс-сериализатор

    """

    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    permission_classes = (ApiUserPermission,)
    filter_backends = (DjangoFilterBackend,)
    filterset_fields = ('category',)
    http_method_names = ['get', 'post', 'delete']


@extend_schema(tags=['Product Categories'])
@extend_schema_view(
    list=extend_schema(
        operation_id='api_products_category_list',
        summary='Получить список категорий',
        description=' ',
        responses={
            (status.HTTP_200_OK, 'application/json'): ProductCategorySerializer,
            (status.HTTP_401_UNAUTHORIZED, 'application/json'): DetailMessageSerializer,
        },
    ),
    retrieve=extend_schema(
        operation_id='api_catgory_by_id',
        summary='Получить категорию по id',
        description=' ',
        parameters=[
          OpenApiParameter(
              name='id',
              type=int,
              location=OpenApiParameter.PATH,
              required=True,
              description='id категории товара'
          )
        ],
        responses={
            (status.HTTP_200_OK, 'application/json'): ProductCategorySerializer,
            (status.HTTP_401_UNAUTHORIZED, 'application/json'): DetailMessageSerializer,
            (status.HTTP_404_NOT_FOUND, 'application/json'): DetailMessageSerializer,
        }
    ),
    create=extend_schema(
        operation_id='api_category_create',
        summary='Добавить категорию товара',
        description=' ',
        responses={
            (status.HTTP_201_CREATED, 'application/json'): ProductCategorySerializer,
            (status.HTTP_401_UNAUTHORIZED, 'application/json'): DetailMessageSerializer,
            (status.HTTP_403_FORBIDDEN, 'application/json'): DetailMessageSerializer
        }
    ),
    destroy=extend_schema(
        operation_id='api_category_destroy',
        summary='Удалить категорию товара',
        description=' ',
        parameters=[
          OpenApiParameter(
              name='id',
              type=int,
              location=OpenApiParameter.PATH,
              required=True,
              description='id категории товара, которую необходимо удалить'
          )
        ],
        responses={
            status.HTTP_204_NO_CONTENT: None,
            (status.HTTP_401_UNAUTHORIZED, 'application/json'): DetailMessageSerializer,
            (status.HTTP_403_FORBIDDEN, 'application/json'): DetailMessageSerializer
        }
    )

)
class APIProductCategoryViewSet(ModelViewSet):

    """Создает ресурс-категория товара

    Переопределены атрибуты:
        1. serializer_class - ссылка на класс сериализатора

    """
    queryset = ProductCategory.objects.all()
    serializer_class = ProductCategorySerializer
    permission_classes = (ApiUserPermission,)
    http_method_names = ['get', 'post', 'delete']


@login_required
def add_product(request: HttpRequest, product_id: int):
    """Добавляет товар в корзину пользователя и возвращает текущую страницу

    Если для указанного товара, не найдена корзина, создается новая запись .
    Если корзина для товара уже существует, уведичивается поле total/

    """
    product = get_object_or_404(klass=Product, id=product_id)
    try:
        buscet = Buscet.objects.get(user=request.user, product=product)
        buscet.total += 1
        buscet.save()
    except ObjectDoesNotExist:
        Buscet.objects.create(user=request.user, product=product, total=1)
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


def remove_product(request: HttpRequest, buscet_id: int):
    """Удаляет корзину товара и возвращает текущую страницу"""
    Buscet.objects.filter(id=buscet_id).delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

products/templates/products/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    {% block t_styles %}{% endblock %}

</head>

<body>
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">Store</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'ns_products:prod_page' %}">Каталог <i class="fas fa-shopping-bag"></i> </a>
                </li>

                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="fas fa-user-circle"></i>
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li>
                                <a class="dropdown-item" href="{% url 'users:profile' user.id %}">Профиль</a>
                            </li>
                            <li><a class="dropdown-item" href="{% url 'orders:show' %}">Заказы</a></li>
                            {% if user.is_superuser or user.is_staff %}
                                <li><a class="dropdown-item" href="{% url 'admin:index' %}">Админ-панель</a></li>
                            {% endif %}
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'users:logout' %}">
                                    Выйти
                                </a>
                            </li>
                        </ul>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Войти <i class="fas fa-sign-in-alt"></i></a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
{% block content %}{% endblock %}
{% block footer %}{% endblock %}

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js'%}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

<!-- FontAwesome script -->
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>

</body>

</html>

products/templates/products/buscets.html
{% load humanize %}
{% if buscets %}
<div class="col-lg-5">
    <h4 class="mt-5 mb-5 d-flex justify-content-between align-items-center mb-5">
        Корзина <span class="badge badge-secondary badge-pill">{{ buscets.calc_total_products }}</span>
    </h4>
    {% for buscet in buscets %}
        <div class="card mb-3">
        <div class="card-body">
            <h5 class="card-title">{{ buscet.product__name }}</h5>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item bg-light">
                <div class="row text-center">
                    <div class="col-lg-4">
                        <input name="basketID" type="number" class="form-control"
                               value="{{ buscet.total }}" min="0">
                    </div>
                    <div class="col-lg-4">{{ buscet.price|intcomma }} руб.</div>
                    <div class="col-lg-4">
                        <a href="{% url 'ns_products:remove_product' buscet.id %}">
                            <i class="fas fa-trash"></i>
                        </a>
                    </div>
                </div>
            </li>
        </ul>
    </div>
    {% endfor %}

    <div class="card mb-3">
        <div class="card-footer">
            <p class="float-left">Итого</p>
            <h4 class="float-right">{{ buscets.calc_total_price|intcomma }} руб.</h4>
        </div>
    </div>
    <a class="btn btn-success btn-lg float-right" href="{% url 'orders:create' %}">
        Оформить заказ
    </a>
</div>
{% else %}
<h4 class="mt-5 mb-5 text-center">Корзина пуста</h4>
{% endif %}

products/templates/products/index.html
{% extends 'products/base.html' %}
{% load static %}
{% block title %}{{ title }}{% endblock %}
{% block t_styles %}
<link href="{% static 'vendor/css/index.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
<section>
    <!--    <div class="alert alert-light text-center" role="alert">-->
    <!--        Информационное сообщение-->
    <!--    </div>-->
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <h1 class="mt-5">Store</h1>
                <p>
                    Новые образы и лучшие бренды на Store.
                    Бесплатная доставка по всему миру! Аутлет: до -70% Собственный бренд. -20% новым покупателям.
                </p>
                <button id="start-purchase-btn" type="button" class="btn btn-lg" >
                    <a id="start-purchase-link" href="{% url 'ns_products:prod_page' %}">
                        Начать покупки
                    </a>
                </button>
            </div>
        </div>
    </div>
</section>
{% endblock %}

products/templates/products/products.html
{% extends 'products/base.html' %}
{% load static %}

{% block title %}{{title}}{% endblock %}

{% block t_styles %}
<link href="{% static 'vendor/css/products.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="container">

    <div class="row">

        <div class="col-lg-3">

            <h1 class="my-4">Store</h1>
            <div class="list-group">
                {% for category in categories %}
                    <a href="{% url 'ns_products:category' category.id %}" class="list-group-item">{{ category.name }}</a>
                {% endfor %}
            </div>

        </div>
        <!-- /.col-lg-3 -->

        <div class="col-lg-9">

            <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active">
                        <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-1.jpg' %}" alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-2.jpg' %}" alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-3.jpg' %}" alt="Third slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

            <div class="row">
                {% for product in products %}
                    <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100">
                        <a href="#">
                            <img class="card-img-top"
                                 src="{{ product.image.url }}"
                                 alt="">
                        </a>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="#">{{ product.name }}</a>
                            </h4>
                            <h5>{{ product.price }} руб.</h5>
                            <p class="card-text">{{ product.description }}</p>
                        </div>
                        <div class="card-footer text-center">
                            <a class="btn btn-outline-success" href="{% url 'ns_products:add_product' product.id %}">Отправить в корзину</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>

            {% if is_paginated %}
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
                        <a class="page-link" href="?page={% if page_obj.has_previous %}{{ page_obj.previous_page_number }}
                        {% else %}#{% endif %}" tabindex="-1"
                           aria-disabled="true">Предыдущая</a>
                    </li>
                    {% for page in page_obj.paginator.page_range %}
                        <li class="page-item"><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
                    {% endfor %}
                    <li class="page-item {% if not page_obj.has_next %} disabled {% endif %}">
                        <a class="page-link" href="?page={% if page_obj.has_next %}{{ page_obj.next_page_number }}
                        {% else %}#{% endif %}">Следующая</a>
                    </li>
                </ul>
            </nav>
            {% endif %}
        </div>

    </div>

</div>
{% endblock %}

{% block footer %}
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Store 2022</p>
    </div>
</footer>
{% endblock %}